{{- if not .Values.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ollama-queue-proxy.fullname" . }}
  labels:
    {{- include "ollama-queue-proxy.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
{{- end }}
